blog/urls.py
# from django.conf.urls import patterns, url
# from django.views.generic import ListView, DetailView
# from blog.models import Post

# urlpatterns = [,
#   url(r'^$', 'blog.views.index'),
#   # Index, with pagination
#   # url(r'^(?P<page>\d+)?/?$', ListView.as_view(
#   #   model = Post,
#   #   paginate_by = 5,
#   #   )),

#   # Individual posts
#   url(r'^(?P<year>\d{4})/(?P<month>\d{1,2})/(?P<slug>[a-zA-Z0-9-]+)/$', 'blog.views.post_detail'),
# ]

from django.conf.urls import patterns, url
from django.views.generic import ListView, DetailView
# from blog.models import Post, Tag

urlpatterns = [
  url(r'^$', 'blog.views.index'),

  # Individual posts
  url(r'^(?P<slug>[a-zA-Z0-9-]+)/$', 'blog.views.post_detail'),

  #posts with a specifc tag
  url(r'^tagged/(?P<tag>[a-zA-Z0-9-]+)/$', 'blog.views.tagged', name="posts_tagged")
]

ifj/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.views.generic import TemplateView

urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),
    #django app urls
    url(r'^playground/', include('playground.urls', namespace='playground')),
    url(r'^blog/', include('blog.urls', namespace='blog')),
    #static pages urls
    url(r'^about-me/', 
      TemplateView.as_view(template_name='pages/about.html'),
      name='about-me'),
    url(r'^find-me/', 
      TemplateView.as_view(template_name='pages/find-me.html'),
      name='find-me'),
    url(r'^resu-me/', 
      TemplateView.as_view(template_name='pages/resume.html'),
      name='resu-me'),
    url(r'^$', 
      TemplateView.as_view(template_name='pages/about.html'),
      name='landing'),
]

# from django.conf.urls import patterns, include, url
# from django.contrib import admin
# from staticpages.views import HomeView, AboutView, FindMeView, ResumeView

# admin.autodiscover()

# urlpatterns = patterns('',

#   #admin urls
#   url(r'^admin/', include(admin.site.urls)),

#   #photography gallery urls
#   url(r'^photography/', include('photography.urls')),
#   # url(r'^photologue/', include('photologue.urls', namespace='photologue')),

#   #django app urls
#   url(r'^blog/', include('blogengine.urls')),
#   url(r'^playground/', include('playground.urls')),

#   #static pages urls
#   url(r'^about-me/', AboutView.as_view()),
#   url(r'^find-me/', FindMeView.as_view()),
#   url(r'^resume/', ResumeView.as_view()),
#   url(r'^$', AboutView.as_view())
#   # url(r'^$', HomeView.as_view())
  
# )

  # url(r'^about-me/', 
 #    TemplateView.as_view(template_name='templates/about.html'),
 #    name='about-me'),
  # url(r'^find-me/', 
 #    TemplateView.as_view(template_name='templates/find-me.html'),
 #    name='find-me'),
 #  url(r'^resu-me/', 
 #    TemplateView.as_view(template_name='templates/resume.html'),
 #    name='resu-me'),

playground/urls.py
from django.conf.urls import patterns, url
from django.views.generic import ListView, DetailView
from playground.models import Project

urlpatterns = [
	url(r'^$', 'playground.views.index'),

	# Individual posts
	url(r'^(?P<slug>[a-zA-Z0-9-]+)/?$', 'playground.views.project_detail'),
]

blog/models.py
from django.db import models
from django.utils import timezone

class Tag(models.Model):
  content = models.CharField(max_length=200, unique=True, default=None)
  slug = models.SlugField(max_length=200, unique=True)
  created_on  = models.DateTimeField( default=timezone.now)

  def __str__(self):
      return self.slug

  def get_absolute_url(self):
      # return reverse("tag_index", kwargs={"slug": self.slug})
      return "/blog/tagged/%s/" % (self.slug)


# Create your models here.
class Post(models.Model):
  title = models.CharField(max_length = 200)
  pub_date = models.DateTimeField()
  text = models.TextField()
  tags = models.ManyToManyField(Tag, blank=True)
  slug = models.SlugField(max_length = 200, unique = True)
  
  def get_absolute_url(self):
    return "/blog/%s/" % (self.slug)

  def __str__(self):
    return self.title

  class Meta:
    ordering = ["-pub_date"]

playground/models.py
# Create your models here.
from django.db import models

# Create your models here.

def thumbnail_image_path(instance, filename):
  # file will be uploaded to MEDIA_ROOT/user_<id>/<filename>
  return 'playground/project_{0}/thumbnail/{1}'.format(instance.slug, filename)

def image_path(instance, filename):
  # file will be uploaded to MEDIA_ROOT/user_<id>/<filename>
  return 'playground/project_{0}/screenshots/{1}'.format(instance.proj.slug, filename)

class ProjectImage(models.Model):
  proj = models.ForeignKey('Project', null=True)
  caption = models.TextField()
  projimg = models.ImageField(upload_to=image_path, null=True) #ideally also include project name

  # def __str__(self):
  #   return self.url

class Project(models.Model):
  #to do: multiple image uploads
  title = models.CharField(max_length = 200)
  pub_date = models.DateTimeField('date added to site')
  projurl = models.URLField(null=True, blank=True)
  completion_date = models.DateTimeField('date completed')
  thumbnail = models.ImageField(upload_to=thumbnail_image_path, null=True)
  objective = models.TextField(null=True, blank=True)
  description = models.TextField()
  solution = models.TextField(null = True, blank=True)
  slug = models.SlugField(max_length = 40, unique = True)
  gallery = models.BooleanField(default=False)

  def get_absolute_url(self):
    return "/playground/%s/" %(self.slug)

  def __unicode__(self):
    return self.title

  class Meta:
    ordering = ["-pub_date"]


#these could be many to many relationships instead to speed up the data
class ProjectTech(models.Model):
  project = models.ForeignKey(Project, null = True)
  name = models.CharField(max_length = 200)
  # def __unicode__(self):
  #   return self.name

class ProjectColor(models.Model):
  project = models.ForeignKey(Project, null = True)
  hexa = models.TextField(max_length=10)
    # def __unicode__(self):
  #   return self.color

blog/views.py
from blog.models import Post
from django.shortcuts import render
# from django.http import HttpResponse

# Create your views here.
def index(request):
  # get the blog posts that are published
  posts = Post.objects.all
  # now return the rendered template
  return render(request, 'blog/post_list.html', {'object_list': posts})

def post_detail(request, slug):
  post = Post.objects.get(slug=str(slug))
  return render(request, 'blog/post_detail.html', {'post': post})

def tagged(request, tag):
  posts = Post.objects.filter(tags__slug=tag)
  return render(request, 'blog/post_list.html', {'object_list': posts})

playground/views.py
# from django.shortcuts import render


# def index(request):
# 	# get the blog posts that are published
# 	projects = Project.objects.all
# 	# now return the rendered template
# 	return render(request, 'playground/index.html', {'object_list': projects})


from playground.models import Project
from django.shortcuts import render
# from django.http import HttpResponse

# Create your views here.
def index(request):
	# get the blog posts that are published
	projects = Project.objects.all
	# now return the rendered template
	return render(request, 'playground/project_list.html', {'project_list': projects})

def project_detail(request, slug):
	project = Project.objects.get(slug=str(slug))
	return render(request, 'playground/project_detail.html', {'project': project})

templates/base.html
<!doctype html>

<html lang="en">
<head>
  {% load static %}
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta name="description" content="im-ifj: the website of Isabella Jorissen">
  <meta name="author" content="ifjorissen">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta property="og:site_name" content="im-ifj" />
  <meta property="og:title" content="im-ifj"/>
  <meta property="og:description" content="im-ifj: the website of Isabella Jorissen" />
  <meta property="og:image" content=""> <!-- TODO logo -->
  <meta property="og:url" content="im-ifj.com">
  
  <title>{% block title %}im-ifj{% endblock %}</title>
  <link rel = "stylesheet" href="//maxcdn.bootstrapcdn.com/font-awesome/4.3.0/css/font-awesome.min.css">
  {% block stylesheets %}
 	<link href="{% static 'im-ifj/css/main.css' %}" rel="stylesheet">
  {% endblock %}

  <!--[if lt IE 9]>
  <script src="http://html5shiv.googlecode.com/svn/trunk/html5.js"></script>
  <![endif]-->
</head>

<body>
	<!-- <header>{% include 'includes/nav.html' %}</header> -->
	<main>{% block content %}{% endblock %}</main>
  <script src="{% static 'jquery/dist/jquery.min.js' %}"></script>
  <script src="{% static 'materialize/dist/js/materialize.min.js' %}"></script>
	<!-- <footer>{% include 'includes/footer.html' %}</footer> -->
 	<!-- // <script src="//ajax.googleapis.com/ajax/libs/jquery/1.11.2/jquery.min.js"></script> -->
<!-- 	// <script src="//code.jquery.com/ui/1.11.4/jquery-ui.min.js"></script> -->
  <!-- // <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.95.3/js/materialize.min.js"></script> -->
  <script src="{% static 'im-ifj/js/app.min.js' %}"></script>
  {% if debug %}
    <script src="//localhost:35729/livereload.js"></script>
  {% endif %}
<!--  <script src="js/scripts.js"></script> -->

			<!-- Google Analytics: change UA-XXXXX-X to be your site's ID. -->
	<script>
		(function(b,o,i,l,e,r){b.GoogleAnalyticsObject=l;b[l]||(b[l]=
		function(){(b[l].q=b[l].q||[]).push(arguments)});b[l].l=+new Date;
		e=o.createElement(i);r=o.getElementsByTagName(i)[0];
		e.src='//www.google-analytics.com/analytics.js';
		r.parentNode.insertBefore(e,r)}(window,document,'script','ga'));
		ga('create','UA-XXXXX-X');ga('send','pageview');
	</script>
</body>
</html>

templates/blog/b_base.html
{% extends "base.html"%}
{% load static %}
{% block stylesheets %}
   <!--  <link rel="stylesheet" href="{{STATIC_URL}}blog/blog.css"> -->
    <link rel="stylesheet" href="{% static 'blog/css/main.css' %}">
{% endblock %}

{% block title %} B.log() {% endblock %}

{% block content %}
	<section class = "row">
		{% include "includes/nav.html" %}
		<section id="posts-wrapper" class = "col s12 l10 offset-l2">
		{% block posts %}{% endblock %}
		</section>
	</section>
{% endblock %}

templates/blog/post_detail.html
{% extends "blog/b_base.html" %}

{% load custom_markdown %}
{% block posts %}
<section class="row">
<section class="col l9 s10 offset-l2 offset-s1">
	<section class="post-object detail">
	  <div class="post-header right-align">
      <h2>{{post.title}}</h2>
                <span class="date">{{post.pub_date}}</span>
                {% if post.tags.all %}
               <!--  <p class="pre">Tagged with -->
                <span>&#149 </span>
                {% for tag in post.tags.all %}
                <span><a class="tag" href="{{tag.get_absolute_url}}">{{tag.slug}}</a>&nbsp</span>
                {% endfor %}
                </p>
                {% endif %}
	  </div>
	  <section class="post_body flow-text">
	      {{post.text|custom_markdown}}
	  </section>
	</section>
</section>
</section>
{% endblock %}

{% block footer %}
<div class = "pagination_footer">
    <p>Copyright &copy; {% now "Y" %}</p>
</div>
{% endblock %}

templates/blog/post_list.html
{% extends "blog/b_base.html" %}
{% load custom_markdown %}
{% block posts %}

{% for post in object_list %}
<section class="row">
    <section class="col l8 s10 offset-l2 offset-s1">
        <section class ="post-object ">
            <div class="post-header">
                <h3><a href = "{{post.get_absolute_url}}">{{post.title}}</a></h3>
               <!--  <p><span class="pre">Posted on </span> -->
                <span class="date">{{post.pub_date}}</span>
                {% if post.tags.all %}
               <!--  <p class="pre">Tagged with -->
                <span>&#149 </span>
                {% for tag in post.tags.all %}
                <span><a class="tag" href="{{tag.get_absolute_url}}">{{tag.slug}}</a>&nbsp</span>
                {% endfor %}
                </p>
                {% endif %}
            </div>
            <div class="post-body flow-text">
                {{post.text|custom_markdown | truncatewords:250}} 
            </div>
        </section>
    </section>
</section>
{% empty %}
<section class="row">
    <section class="col l8 s10 offset-l2 offset-s1">
        <section class ="post-object ">
            <div class="post-header">
                <h3>Sorry, there aren't any post here right now</h3>
               <!--  <p><span class="pre">Posted on </span> -->
            </div>
            <div class="post-body flow-text">
                (I'll try to write some soon!)
            </div>
        </section>
    </section>
</section>
{% endfor %}

{% endblock %}

templates/includes/nav.html
<nav role = "navigation" id = "navigation" class="z-depth-2 col l2">
	 <ul class="left hide-on-med-and-down">
		 <li class ="hex-wrapper">
		 		<div class="hex is-loading">
				  <div class="line1"></div>  
				  <div class="line2"></div>  
				  <div class="line3"></div>  
				  <div class="line4"></div>  
				  <div class="line5"></div>
				  <div class="line6"></div>
				</div>
				<div class="hex2 is-loading">
				  <div class="line1"></div>  
				  <div class="line2"></div>  
				  <div class="line3"></div>  
				  <div class="line4"></div>  
				  <div class="line5"></div>
				  <div class="line6"></div>
				</div>
			</li>
			<li class="center-align"><a href="/about-me/">About Me</a></li>
			<li class="center-align"><a href="/blog/">B.log()</a></li>
			<li class="center-align"><a href="/playground/">Playground</a></li>
			<li class="center-align"><a href="/find-me/">Find Me</a></li>
			<li class="center-align"><a href="/resu-me/">Resume</a></li>
			<li>
			{% include "includes/footer.html" %}
			</li>
  </ul>

  <ul id="slide-out" class="side-nav">
		 <li class ="hex-wrapper">
	 		<div class="hex is-loading">
			  <div class="line1"></div>  
			  <div class="line2"></div>  
			  <div class="line3"></div>  
			  <div class="line4"></div>  
			  <div class="line5"></div>
			  <div class="line6"></div>
			</div>
			<div class="hex2 is-loading">
			  <div class="line1"></div>  
			  <div class="line2"></div>  
			  <div class="line3"></div>  
			  <div class="line4"></div>  
			  <div class="line5"></div>
			  <div class="line6"></div>
			</div>
		</li>
			<li class="center-align"><a href="/about-me/">About Me</a></li>
			<li class="center-align"><a href="/blog/">B.log()</a></li>
			<li class="center-align"><a href="/playground/">Playground</a></li>
			<li class="center-align"><a href="/find-me/">Find Me</a></li>
			<li class="center-align"><a href="/resu-me/">Resume</a></li>
			<li>
			{% include "includes/footer.html" %}
			</li>
  </ul>
  <a href="#" data-activates="slide-out" class="button-collapse"><i class="burger fa fa-bars"></i></a>
</nav>

templates/pages/about.html
{% extends "base.html" %}
{% block title%} ifj {% endblock %}
{% block content %}
	<section class="row">
	{% include "includes/nav.html" %}
		<section id="me-wrapper" class="col s12 l10 offset-l2">
		<section class="row valign-wrapper">
			<section id = "me" class="valign col l8 s10 offset-l2 offset-s1"> 
				<p class = "flow-text">Hi, I'm Isabella. I'm a senior math major (with a concentration in computer science) at Reed College. I can't say that all those math classes have made me faster at calculating tips, but I've developed a soft spot for clean code and proofs by reduction.</p>
				<p class="flow-text">When it comes to programming, I'm a sucker for a smooth workflow and good documentation. One of my favorite parts about beginning a new project is the process of stitching all the technologies together seamlessly. Though my projects vary in scope and language, Sublime Text has remained my primary text editor and I've been using oh-my-zsh to pimp out my shell since 2012.</p>
				<section class="row" id="more">
					<section class = "col s12">
						<section class="row">
						<ul id="books" class="col s12 m8 l8">
							<li class="header">Books:</li>
							<li>Seiobo There Below by László Krasznahorkai</li>
							<li>Can't and Won't by Lydia Davis</li>
							<li>Museum of Eterna's Novel (The First Good Novel) by Macedonio Fernández</li>
							<li>The Brothers Karamazov by Fyodor Dostoyevsky</li>
							<li>Nikolai Gogol by Vladimir Nabokov</li>
						</ul>

						<ul id="places" class="col s12 m4 l4">
							<li class="header">Places:</li>
							<li>Oaks Bottom Park</li>
							<li>Skidmore Bluffs</li>
							<li>Reed College Performing Arts Building</li>
						</ul>
						</section>
						<section class="row">
						<ul id="music" class="col s12 m8 l8">
							<li class="header">Albums:</li>
							<li>Kid A by RadioHead</li>
							<li>The Moon & Antarctica by Modest Mouse</li>
							<li>An Awesome Wave by alt-J</li>
							<li>LP1 by FKA twigs</li>
							<li>Sylvan Esso by Sylvan Esso</li>
						</ul>

						<ul id="things" class="col s12 m4 l4">
							<li class="header">Things:</li>
							<li>Pilot .4mm Hi-Tec C Pen</li>
							<li>Soft Cover Moleskine</li>
							<li>Rubik's Cube</li>
						</ul>
						</section>
					</section>
				</section>
			</section>
		</section>	
		</section>
 </section>
<!-- 	<footer>
	</footer> -->
{% endblock %}		

templates/pages/find-me.html
{% extends "base.html" %}
{% block title%} ifj {% endblock %}
{% block content %}
<section class="row">
  {% include "includes/nav.html" %}
  <section id="find-me-wrapper" class="col s12 l10 offset-l2 valign-wrapper"> 
  <div class = "valign col l4 m4 s8 find_me_links">
    <a id ="github" href="https://github.com/ifjorissen" class="waves-effect waves-light btn-large"><i class="fa fa-github-alt"></i></a>
    <a href="https://www.linkedin.com/pub/isabella-jorissen/59/48a/80" class="waves-effect waves-light btn-large"><i class="fa fa-linkedin"></i></a>
    <a href="https://www.twitter.com/ifjorissen" class="waves-effect waves-light btn-large"><i class="fa fa-twitter"></i></a>
  </div>
  </section>
</section>
{% endblock %}    

templates/pages/resume.html
{% extends "base.html" %}
{% load static %}
{% block title%} ifj {% endblock %}
{% block content %}
<section class="row">
		{% include "includes/nav.html" %}
  	<section id = "resume" class="col s12 m12 l10 offset-l2 valign-wrapper"> 
    <object data="{% static 'ifjorissen_resumeS15.pdf' %}" type="application/pdf" width="100%" height="100%">
   
    alt:<a href="{% static 'ifjorissen_resumeS15.pdf' %}">here!</a></p>
    
  </object>
  </section>
</section>
{% endblock %}    

templates/playground/p_base.html
{% extends "base.html"%}
{% load static %}
{% block stylesheets %}
	<link rel="stylesheet" href="{% static 'playground/css/main.css'%}">
{% endblock %}

{% block title %} ifj/playground {% endblock %}

{% block content %}
	<section class = "row">
		{% include "includes/nav.html" %}
		<section id = "proj-wrapper" class = "col s12 l10 offset-l2">
		{% block projects %}{% endblock %}
		</section>
	</section>
{% endblock %}

templates/playground/project_detail.html
{% extends "playground/p_base.html" %}
{% block title %} ifj/playground {% endblock %}
{% load static %}

{% load custom_markdown %}
{% block projects %}
  <section class="row">
    <section class="col l9 s10 offset-l2 offset-s1">
      <section class="proj-object">
        <section class="row valign-wrapper proj-header">
          <div class="col l2 s2 m2 valign"><img class="circle responsive-img" src="{{project.thumbnail.url}}"></div>
          <div class="col l10 m10 s10 right-align">
            <h2><a href = "{{project.get_absolute_url}}">{{project.title}}</a></h2>
            {% if project.projurl %}
            <span class="h4">Project URL:</span><span><a href="{{project.projurl}}"> {{project.projurl}}</a></span> <br>
            {% endif %}
            <span class="h4">Completed On:</span><span> {{project.completion_date}}</span></br>
          </div>
        </section>
        <section class="row">
          <section class="col l12 m12 s12 proj-body flow-text">
          {% if project.objective %}
            <h5 class="subheader">Objective:</h5>
            {{project.objective|custom_markdown}}<br>
          {% endif %}
            <h5 class="subheader">Description:</h5>
            {{project.description|custom_markdown}}</br>
          {%if project.solution %}      
	          <h5 class="subheader">Solution:</h5>
            {{project.solution|custom_markdown}}</br>
          {% endif %} 
          </section>
          <section class="col l12 m12 s12 proj-images flow-text">
              <h5 class="subheader">Project Stills</h5>
              {% if project.gallery %}
                {% for img in project.projectimage_set.all reversed %}
                <section class="row">
                <div class="col l10 m10 s12 proj-image-wrapper">
                  <div class="proj-img">
                    <img class="responsive-img" src="{{img.projimg.url}}">
                    <p class="img-caption">{{img.caption}}</p>
                  </div>
                </div>
                </section>
                {% endfor %}
              {% else %}
                <section class="row">
                {% for img in project.projectimage_set.all reversed %}
                <div class="col l6 m6 s12 proj-image-wrapper">
                  <div class="proj-img">
                    <img class="responsive-img" src="{{img.projimg.url}}">
                    <p class="img-caption">{{img.caption}}</p>
                  </div>
                </div>
                {% if forloop.counter|divisibleby:2 %}
                </section>
                <section class="row">
               {% endif %}
              {% endfor %}
              </section>
              {% endif %}
           </section>
        </section>
      </section>
    </section>
  </section>
{% endblock %}

{% block footer %}
<!-- <div class = "pagination_footer">
  {% if page_obj.has_previous %}
  <h5 class = "prev"><a href = "/playground/{{page_obj.previous_page_number}}/">Previous Page</a></h5>
  {% endif %} -->

  {% if page_obj.has_next %}
  <h5 class ="next"><a href = "/playground/{{page_obj.next_page_number}}/">Next Page</a></h5>
  {% endif %}
</div>
{% endblock %}

templates/playground/project_list.html
{% extends "playground/p_base.html" %}
{% block title %} ifj/playground {% endblock %}
{% load custom_markdown %}
{% load static %}

{% block projects %}
{% if project_list %}
<section class="row">
  <section class="col l8 m10 s10 offset-l2 offset-m1 offset-s1">
    <section class="row">
    {% for project in project_list %}
    {% cycle ' ' 'offset-l2' as lgcol silent%}
    <section class="col l5 m6 s12 {{ lgcol }}">
      <section class="card proj-object">
          <div class="card-image"><img class="responsive-img" src="{{project.thumbnail.url}}"></div>
          <div class="card-content">
            <h4>{{project.title}}</h4>
            <p class = "flow-text">{{project.objective}}</p>
          </div>
          <div class="card-action">
            <a href = "{{project.get_absolute_url}}"> More about this project <span class="secondary-content"><i class="fa fa-long-arrow-right"></i></span></a>
          </div>
      </section>
    </section>
      {% if forloop.counter|divisibleby:2 %}
      </section>
      <section class="row">
      {% endif %}
      {% endfor %}
    </section>
  </section>
</section>
{% else %}
      <div  id="coming-soon" class="col s10 l6 offset-s1 offset-l3">
        <div class="card-panel center-align">
          <span> Project Descriptions Coming Soon!</span>
        </div>
      </div>
{% endif %}


{% endblock %}

{% block footer %}
<div class = "pagination_footer">
  {% if page_obj.has_previous %}
  <h5 class = "prev"><a href = "/playground/{{page_obj.previous_page_number}}/">Previous Page</a></h5>
  {% endif %}

  {% if page_obj.has_next %}
  <h5 class ="next"><a href = "/playground/{{page_obj.next_page_number}}/">Next Page</a></h5>
  {% endif %}
</div>
{% endblock %}

templates/playground/project_list_old.html
{% extends "playground/p_base.html" %}
{% block title %} ifj/playground {% endblock %}
{% load custom_markdown %}

{% block projects %}

{% if project_list %}
  {% for project in project_list %}
  <section class="row">
    <section class="col l7 s10 offset-l2 offset-s1">
      <section class="proj-object">
        <div class="proj-header">
        <!-- add a project thumbnail!?! -->
            <span><img class="responsive-img" src="{{STATIC_URL}}{{img.thumbnail}}"></span>
            <h2><a href = "{{project.get_absolute_url}}">{{project.title}}</a></h2>
            <span class="h5">Project URL:</span><span><a href="{{project.projurl}}"> {{project.projurl}}</a></span> <br>
            <span class="h5">Objective:</span><span> {{project.objective}}</span> 
        </div>
        </section>
      </section>
    </section>
  </section>
  {% endfor %}
{% else %}
  <div  id="coming-soon" class="col s10 l6 offset-s1 offset-l3">
    <div class="card-panel center-align">
      <span> Project Descriptions Coming Soon!</span>
    </div>
  </div>
{% endif %}

{% endblock %}

{% block footer %}
<div class = "pagination_footer">
  {% if page_obj.has_previous %}
  <h5 class = "prev"><a href = "/playground/{{page_obj.previous_page_number}}/">Previous Page</a></h5>
  {% endif %}

  {% if page_obj.has_next %}
  <h5 class ="next"><a href = "/playground/{{page_obj.next_page_number}}/">Next Page</a></h5>
  {% endif %}
</div>
{% endblock %}



2.0:
{% if project_list %}
<!--   {% for project in project_list %} -->
  <section class="row">
    <section class="col l7 s10 offset-l2 offset-s1">
    <section class="row">
    <section class="col l6 m6 s12">
    {% for project in project_list %}
      <section class="card proj-object">
        <div class="proj-header">
        <!-- add a project thumbnail!?! -->
            <div class="card-image"><img class="responsive-img" src="{% get_static_prefix %}{{project.thumbnail}}"></div>
            <div class="card-content">
              <h2>{{project.title}}</h2>
              <p class = "flow-text">{{project.objective}}</p>
            </div>
            <div class="card-action">
              <a href = "{{project.get_absolute_url}}">Get the Details <span class="secondary-content"><i class="mdi-action-trending-neutral"></i></span></a>
            </div>
        </div>
      </section>
    {% if forloop.counter|divisibleby:2 %}
    </section>
      <section>
      {% endif %}
      {% endfor %}
      </section>
    </section>
  </section>
</section>
  {% endfor %}
{% else %}
  <div  id="coming-soon" class="col s10 l6 offset-s1 offset-l3">
    <div class="card-panel center-align">
      <span> Project Descriptions Coming Soon!</span>
    </div>
  </div>
{% endif %}